# Выберем базовый образ Node.js
FROM node:20

# Установим рабочую директорию
WORKDIR /hse-project

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Установим зависимости
RUN npm install

# Копируем исходный код приложения
COPY . .

EXPOSE 3000
EXPOSE 3001


CMD ["npm", "start"]